name: Release

on:
  push:
    branches: [main, dev]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    concurrency: release

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install python-semantic-release and build
        run: pip install python-semantic-release build

      - name: Semantic release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          semantic-release version
